(define (* a b)
  (define (halve x) (/ x 2))
  (define (double x) (+ x x))
  (define (even? x) (= (remainder x 2) 0))
  (define (*-iter x y counter)
    (cond ((= counter 0) x)
	  ((even? counter) (*-iter x (double y) (halve counter)))
	  (else (*-iter (+ x y) y (- counter 1)))
	  )
    )
  (*-iter 0 a b)
  )
