(define (smallest-divisor n)
  (define (square x) (* x x))
  (define (smallest-divisor-iter counter)
    (cond ((> (square counter) n) n)
	  ((= (remainder n counter) 0) counter)
	  (else (smallest-divisor-iter (+ 1 counter))))
    )
  (smallest-divisor-iter 2)
  )
