#lang sicp
(define (full-ferma n)
  (define (square x) (* x x))
  (define (ferma-test base counter)
    (cond ((= counter 0) 1)
          ((= (remainder counter 2) 0) (remainder (square (ferma-test base (/ counter 2))) n))
          (else (remainder (* (ferma-test base (dec counter)) base) n)))
    )
  (define (check base)
    (cond ((= base 1) (display "Prime"))
          ((= (ferma-test base n) base) (check (dec base)))
          (else (display "Not prime")))
    )
  (check (dec n))
  )